# Generated by Django 5.0.3 on 2024-03-13 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-date_pay',), 'verbose_name': 'оплата', 'verbose_name_plural': 'оплаты'},
        ),
    ]
