# Generated by Django 5.0.3 on 2024-03-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_groups',
            field=models.CharField(choices=[('Students', 'Students'), ('Moderator', 'Moderator')], default='Students', max_length=10, verbose_name='группа пользователя'),
        ),
    ]
