# Generated by Django 5.0.3 on 2024-03-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_user_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_groups',
            field=models.CharField(choices=[('Student', 'Student'), ('Moderator', 'Moderator')], default='Student', max_length=10, verbose_name='группа пользователя'),
        ),
    ]
