# Generated by Django 4.2.11 on 2024-03-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_user_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='Abc', max_length=50, unique=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_groups',
            field=models.CharField(blank=True, choices=[('Member', 'Member'), ('Moderator', 'Moderator')], max_length=10, null=True, verbose_name='группа пользователя'),
        ),
    ]
