# Generated by Django 4.2.11 on 2024-04-05 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_alter_lesson_course'),
        ('users', '0023_subscribetoupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribetoupdate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribe', to='materials.course', verbose_name='курс'),
        ),
        migrations.AlterField(
            model_name='subscribetoupdate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='подписка на обновление'),
        ),
        migrations.AlterField(
            model_name='subscribetoupdate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribe', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
