# Generated by Django 4.2.11 on 2024-04-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_subscribetoupdate_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribetoupdate',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='подписка на обновление'),
        ),
    ]
