# Generated by Django 5.0.3 on 2024-03-21 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_lesson_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('title',), 'verbose_name': 'курс', 'verbose_name_plural': 'курсы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('title',), 'verbose_name': 'урок', 'verbose_name_plural': 'уроки'},
        ),
    ]
